---
title: "homework 4"
author: "Siyu Zou"
date: "2023-10-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Q1

```{r cars}
qt(0.95, 24)
qt(0.05,24)
7-qt(0.95,24)*3/5
7-qt(0.05,24)*3/5

qnorm(0.95)
(2*1.645*3/0.5)^2
(2*qnorm(0.95)*3/0.5)^2

# prove
qt(0.95,390-1) * 3/sqrt(390)
qt(0.05,390-1) * 3/sqrt(390)
```

## F test
```{r f test}
alpha = 0.05
nx = 260
ny = 289
Sx = 7.51
Sy = 8.31
qf(1-alpha/2, nx-1, ny-1) * Sx^2/Sy^2
qf(alpha/2, nx-1, ny-1)* Sx^2/Sy^2

# qf(1-alpha/2, nx-1, ny-1) * Sy^2/Sx^2
# qf(alpha/2, nx-1, ny-1)* Sy^2/Sx^2

sqrt( Sx^2/nx + Sy^2/ny)
```
Equal variance
## pooled variance estimator
```{r pooled variance estimator}
Sp2 = ( (nx-1)*Sx^2 + (ny-1)*Sy^2 ) / (nx + ny -2)
t = qt(1-alpha/2, nx+ny-2)

Xa = 9.78
Xd = 12.83
Xa-Xd + t*sqrt(Sp2)*sqrt(1/nx + 1/ny)
Xa-Xd - t*sqrt(Sp2)*sqrt(1/nx + 1/ny)

# annual 
1/3 * (Xa-Xd + t*sqrt(Sp2)*sqrt(1/nx + 1/ny))
1/3 * (Xa-Xd - t*sqrt(Sp2)*sqrt(1/nx + 1/ny))
```

# Q4
```{r GLR}
p = 1/12
choose(348, 16)*p^16*(1-p)^(348-16)
# equal to PDF
dbinom(16, 348, prob = 1/12)

# CDF: pbinom()
pbinom(16, 348, prob = 1/12)


## question d
qnorm(0.95)
qbinom(0.95,348,prob = 4/12, lower.tail = T )

qt(0.95, 348)

## question e
# CDF: pbinom()
1 - pbinom(139, 348, prob = 4/12)
pbinom(139, 348, prob = 4/12, lower.tail = F)

sum = 0
for (i in 1:16) {
  sum = sum + choose(348,i)*(1/12)^i *(1-1/12)^(348-i)
}
sum



```

# Q5
```{r}
library(dplyr)
## Assume the same variance, different mean
## Under different distribution, the expectation and variance in compared groups are the same (shoule be the same ).
result = data.frame(matrix(NA, 2, 3))
colnames(result) = c('norm', 'chi', 't')
row.names(result) = c('size1=10', 'size2=500')

sim_ttest <- function(alpha = 0.05,
                      sim_times = 10000,
                      size_list = c(10, 500),
                      method = 'norm'){
  p_temp = c()
  for (size in size_list){
    p_list = c()
    for (i in c(1: sim_times)){
      if (method == 'norm'){ # E=\3, var = 6
        data1 = rnorm(size, sqrt(3), 6)
        data2 = rnorm(size, sqrt(3), 6)+0.5
      }
      else if (method == 'chi'){  #E=2, var=6
        data1 = sqrt(3)*rchisq(size, 1)
        data2 = sqrt(3)*rchisq(size, 1)+0.5
      }
      else if (method == 't'){ # E=2, var=6
        data1 = sqrt(2)*rt(size, 3)+sqrt(3)
        data2 = sqrt(2)*rt(size, 3)+sqrt(3)+0.5
      }
      p_val = t.test(data1, data2)$p.value
      p_list = append(p_list, p_val)
    }
    p_proportion = sum(p_list<alpha) / length(p_list)
    p_temp = append(p_temp, p_proportion)
  }
  return(p_temp)
}
result$norm = sim_ttest(method = 'norm')
result$chi = sim_ttest(method = 'chi')
result$t = sim_ttest(method = 't')
result

size = 10000
data1 = rnorm(size, sqrt(3), 6)
data2 = sqrt(3)*rchisq(size, 1)
data3 = sqrt(2)*rt(size, 3)+sqrt(3)

mean(data1)
mean(data2)
mean(data3)

var(data1)
var(data2)
var(data3)
```


# My answer for Q5
```{r}
cal_p_value <- function(n, distribution = "norm") {
  if (distribution == "norm") {  
    data_1 <- rnorm(n, mean = 1, sd = 3)  # E[x] =0, Var = 3
    data_2 <- rnorm(n, mean = 1, sd = 3)
  } else if (distribution == "chisq") { 
    data_1 <- rchisq(n, df = 1)      # E[x] =1, Var = 2
    data_2 <- rchisq(n, df = 1) 
  } else if (distribution == "t") {
    data_1 <- rt(n, df = 3)   # E[x] =0, Var = 3
    data_2 <- rt(n, df = 3) 
  } 
  p_val <- t.test(data_1, data_2, var.equal = FALSE)$p.value
  return(p_val)
}

n_rep <- 100000
sample_size <- c(10, 400)
distribution <- c("norm", "chisq", "t")
proportion <- matrix(0, nrow = length(sample_size), ncol = length(distribution))


# Set column names and row names
colnames(proportion) <- distribution
rownames(proportion) <- paste("Sample Size =", sample_size)

for (i in 1:length(sample_size)) {
  n <- sample_size[i]
  for (j in 1:length(distribution)) {
    dist <- distribution[j]
    sum <- 0
    p_values <- numeric(n_rep)
    
    for (k in 1:n_rep) {
      test_p <- cal_p_value(n, dist)
      p_values[k] <- test_p
      if (!is.na(test_p) && test_p <= 0.05) {
        sum <- sum + 1 # the total count of p-values below 0.05
      }
    }
    proportion[i, j] <- sum / n_rep
    # proportion_2[i, j] = mean(p_values <= 0.05)
  }
}

proportion  # Proportions of times where P <= 0.05 for different scenarios

```




# BOOK P364
```{r}
y <- 63.5
x <- 59.6
Sx <- 


```















